/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import domain.Radnik;
import javax.swing.JOptionPane;
import ui.clanovi.FormaClanovi;
import ui.knjige.FormaKnjige;
import ui.zaduzenja.FormaZaduzenja;

/**
 *
 * @author Dejan Colic
 */
public class FormaMain extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormaMain.class.getName());
    private Radnik ulogovani;
    FormaClanovi formaClanovi;
    FormaKnjige formaKnjige;
    FormaZaduzenja formaZaduzenja;
    private javax.swing.Timer sessionTimer;
    private long sessionStartMillis;

    /**
     * Creates new form FormaMain
     */
    public FormaMain() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("Biblioteka");
        setActiveRadnik();
        this.sessionStartMillis = System.currentTimeMillis();
        startSessionTimer();
    }

    public FormaMain(Radnik ulogovani) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.ulogovani = ulogovani;
        setTitle("Biblioteka");
        setActiveRadnik();
        this.sessionStartMillis = System.currentTimeMillis();
        startSessionTimer();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDobrodosli = new javax.swing.JLabel();
        lblNazivRadnika = new javax.swing.JLabel();
        lblTrenutnaSesija = new javax.swing.JLabel();
        lblVremeSesije = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnClanovi = new javax.swing.JButton();
        btnKnjige = new javax.swing.JButton();
        btnZaduzenja = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblDobrodosli.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDobrodosli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDobrodosli.setText("Dobrodosli ");

        lblNazivRadnika.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNazivRadnika.setForeground(new java.awt.Color(0, 51, 255));
        lblNazivRadnika.setText("jLabel2");

        lblTrenutnaSesija.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrenutnaSesija.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrenutnaSesija.setText("Trenutna sesija :");

        lblVremeSesije.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVremeSesije.setText("12:44");

        btnLogOut.setText("Zavrsi sesiju");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnClanovi.setText("Rad sa Clanovima");
        btnClanovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClanoviActionPerformed(evt);
            }
        });

        btnKnjige.setText("Rad sa Knjigama");
        btnKnjige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKnjigeActionPerformed(evt);
            }
        });

        btnZaduzenja.setText("Rad sa Zaduzenjima");
        btnZaduzenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaduzenjaActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDobrodosli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTrenutnaSesija, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVremeSesije, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNazivRadnika, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(244, 492, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnZaduzenja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                            .addComponent(btnClanovi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKnjige, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDobrodosli, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNazivRadnika, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrenutnaSesija, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVremeSesije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnClanovi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        btnLogOut.setEnabled(false);
        stopSessionTimer();
        try {
            controller.UIController.getInstance().logout(ulogovani);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri odjavi: " + ex.getMessage());
        } finally {

            dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnClanoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClanoviActionPerformed
        formaClanovi = new FormaClanovi();
        formaClanovi.setVisible(true);
    }//GEN-LAST:event_btnClanoviActionPerformed

    private void btnKnjigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKnjigeActionPerformed
        formaKnjige = new FormaKnjige();
        formaKnjige.setVisible(true);
    }//GEN-LAST:event_btnKnjigeActionPerformed

    private void btnZaduzenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaduzenjaActionPerformed
        formaZaduzenja = new FormaZaduzenja(this.ulogovani);
        formaZaduzenja.setVisible(true);
    }//GEN-LAST:event_btnZaduzenjaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        stopSessionTimer();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormaMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClanovi;
    private javax.swing.JButton btnKnjige;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnZaduzenja;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblDobrodosli;
    private javax.swing.JLabel lblNazivRadnika;
    private javax.swing.JLabel lblTrenutnaSesija;
    private javax.swing.JLabel lblVremeSesije;
    // End of variables declaration//GEN-END:variables

    private void setActiveRadnik() {
        lblNazivRadnika.setText(this.ulogovani.getIme());
    }

    private void startSessionTimer() {
        if (sessionTimer != null && sessionTimer.isRunning()) {
            sessionTimer.stop();
        }
        sessionTimer = new javax.swing.Timer(1000, e -> updateSessionLabel());
        sessionTimer.setInitialDelay(0);
        sessionTimer.start();
    }

    private void stopSessionTimer() {
        if (sessionTimer != null) {
            sessionTimer.stop();
        }
    }

    private void updateSessionLabel() {
        long elapsed = System.currentTimeMillis() - sessionStartMillis;
        long seconds = elapsed / 1000;
        long h = seconds / 3600;
        long m = (seconds % 3600) / 60;
        long s = seconds % 60;
        lblVremeSesije.setText(String.format("%02d:%02d:%02d", h, m, s));
    }
}
