/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import controller.Controller;
import domain.Radnik;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import models.TableModelRadnik;
import threads.StartServerThread;

/**
 *
 * @author Dejan Colic
 */
public class FormServerMain extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormServerMain.class.getName());
    StartServerThread sst;
    private TableModelRadnik modelRadnici;

    /**
     * Creates new form FormServerMain
     */
    public FormServerMain() {
        initComponents();
        setServerStatus(false);
        setLocationRelativeTo(null);
        setTitle("Serverski Program");
        prepareTable();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        lblStatus = new javax.swing.JLabel();
        lblStatusPrikaz = new javax.swing.JLabel();
        btnPokreniServer = new javax.swing.JButton();
        btnZaustaviServer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRadnici = new javax.swing.JTable();
        meniKonfiguracija = new javax.swing.JMenuBar();
        menuOpcije = new javax.swing.JMenu();
        menuItemKonfig = new javax.swing.JMenuItem();
        menuItemLogs = new javax.swing.JMenuItem();
        menuItemInfo = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblStatus.setText("Status Servera:");

        lblStatusPrikaz.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblStatusPrikaz.setForeground(new java.awt.Color(255, 0, 0));
        lblStatusPrikaz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatusPrikaz.setText("Neaktivan");

        btnPokreniServer.setText("Pokreni Server");
        btnPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniServerActionPerformed(evt);
            }
        });

        btnZaustaviServer.setText("Zaustavi Server");
        btnZaustaviServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviServerActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista trenutno ulogovanih radnika"));

        tblRadnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRadnici);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        menuOpcije.setText("Opcije");
        menuOpcije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcijeActionPerformed(evt);
            }
        });

        menuItemKonfig.setText("Konfiguracija Servera");
        menuItemKonfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKonfigActionPerformed(evt);
            }
        });
        menuOpcije.add(menuItemKonfig);

        menuItemLogs.setText("Logs");
        menuOpcije.add(menuItemLogs);

        menuItemInfo.setText("Info");
        menuItemInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInfoActionPerformed(evt);
            }
        });
        menuOpcije.add(menuItemInfo);

        meniKonfiguracija.add(menuOpcije);

        setJMenuBar(meniKonfiguracija);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(btnPokreniServer)
                                .addGap(18, 18, 18)
                                .addComponent(btnZaustaviServer))
                            .addComponent(lblStatusPrikaz, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatusPrikaz, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokreniServer)
                    .addComponent(btnZaustaviServer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniServerActionPerformed
        sst = new StartServerThread();
        sst.start();
        setServerStatus(true);
    }//GEN-LAST:event_btnPokreniServerActionPerformed

    private void btnZaustaviServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviServerActionPerformed
        sst.terminateThreads();
        setServerStatus(false);
    }//GEN-LAST:event_btnZaustaviServerActionPerformed

    private void menuOpcijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcijeActionPerformed

    }//GEN-LAST:event_menuOpcijeActionPerformed

    private void menuItemInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemInfoActionPerformed

    private void menuItemKonfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKonfigActionPerformed
        new FormServerConfig().setVisible(true);
    }//GEN-LAST:event_menuItemKonfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormServerMain().setVisible(true));
    }

    private void setServerStatus(boolean active) {
        if (active) {
            lblStatusPrikaz.setText("Aktivan");
            lblStatusPrikaz.setForeground(Color.green);
        } else {
            lblStatusPrikaz.setText("Neaktivan");
            lblStatusPrikaz.setForeground(Color.red);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreniServer;
    private javax.swing.JButton btnZaustaviServer;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusPrikaz;
    private javax.swing.JMenuBar meniKonfiguracija;
    private javax.swing.JMenuItem menuItemInfo;
    private javax.swing.JMenuItem menuItemKonfig;
    private javax.swing.JMenuItem menuItemLogs;
    private javax.swing.JMenu menuOpcije;
    private javax.swing.JTable tblRadnici;
    // End of variables declaration//GEN-END:variables

    private void prepareTable() {
        List<Radnik> sharedRadniciList = new ArrayList<>();
        modelRadnici = new TableModelRadnik(sharedRadniciList);
        Controller.getInstance().setUlogovaniRadnici(sharedRadniciList);
        Controller.getInstance().setModelRadnik(modelRadnici);
        tblRadnici.setModel(modelRadnici);
    }
}
