/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.knjige;

import domain.Knjiga;
import domain.Primerak;
import javax.swing.JOptionPane;
import models.TableModelKnjiga;
import models.TableModelPrimerakTemp;

/**
 *
 * @author Dejan Colic
 */
public class DijalogNovaKnjiga extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DijalogNovaKnjiga.class.getName());
    private TableModelPrimerakTemp primerciModel;
    private TableModelKnjiga knjigaModel;
    private FormaKnjige parentForm;

    /**
     * Creates new form DijalogNovaKnjiga
     *
     * @param parent
     * @param modal
     */
    public DijalogNovaKnjiga(java.awt.Frame parent, boolean modal, TableModelKnjiga knjigaModel, FormaKnjige parentForm) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.knjigaModel = knjigaModel;
        this.parentForm = parentForm;
        primerciModel = new TableModelPrimerakTemp();
        tblPrimerak.setModel(primerciModel);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNaziv = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblIzdavac = new javax.swing.JLabel();
        lblGodina = new javax.swing.JLabel();
        txtIzdavac = new javax.swing.JTextField();
        txtGodina = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrimerak = new javax.swing.JTable();
        btnSacuvajPrimerak = new javax.swing.JButton();
        btnObrisiPrimerak = new javax.swing.JButton();
        btnIzmeniPrimerak = new javax.swing.JButton();
        btnSacuvajKnjigu = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Knjiga"));

        lblNaziv.setText("Naziv :");

        lblAutor.setText("Autor :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNaziv)
                    .addComponent(lblAutor))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNaziv)
                    .addComponent(txtAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Primerci"));

        lblIzdavac.setText("Izdavac :");

        lblGodina.setText("Godina Izdanja :");

        tblPrimerak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrimerak);

        btnSacuvajPrimerak.setText("Sacuvaj Primerak");
        btnSacuvajPrimerak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajPrimerakActionPerformed(evt);
            }
        });

        btnObrisiPrimerak.setText("Obrisi Primerak");
        btnObrisiPrimerak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPrimerakActionPerformed(evt);
            }
        });

        btnIzmeniPrimerak.setText("Izmeni Primerak");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSacuvajPrimerak)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeniPrimerak)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiPrimerak))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIzdavac)
                            .addComponent(lblGodina))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIzdavac)
                            .addComponent(txtGodina, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIzdavac)
                    .addComponent(txtIzdavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGodina)
                    .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvajPrimerak)
                    .addComponent(btnObrisiPrimerak)
                    .addComponent(btnIzmeniPrimerak))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSacuvajKnjigu.setText("Sacuvaj Knjigu");
        btnSacuvajKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajKnjiguActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvajKnjigu)
                        .addGap(18, 18, 18)
                        .addComponent(btnOdustani)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvajKnjigu)
                    .addComponent(btnOdustani))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajPrimerakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajPrimerakActionPerformed
        String izdavac = txtIzdavac.getText().trim();
        String godinaStr = txtGodina.getText().trim();

        if (izdavac.isEmpty() || godinaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Popunite izdavača i godinu.");
            return;
        }

        try {
            int godina = Integer.parseInt(godinaStr);
            Primerak p = new Primerak();
            p.setIzdavac(izdavac);
            p.setGodinaIzdanja(godina);
            primerciModel.addPrimerak(p);

            txtIzdavac.setText("");
            txtGodina.setText("");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Godina mora biti broj.");
        }
    }//GEN-LAST:event_btnSacuvajPrimerakActionPerformed

    private void btnObrisiPrimerakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPrimerakActionPerformed
        int row = tblPrimerak.getSelectedRow();
        if (row >= 0) {
            primerciModel.removePrimerak(row);
        }
    }//GEN-LAST:event_btnObrisiPrimerakActionPerformed

    private void btnSacuvajKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajKnjiguActionPerformed
        String naziv = txtNaziv.getText().trim();
        String autor = txtAutor.getText().trim();

        if (naziv.isEmpty() || autor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Popunite naziv i autora.");
            return;
        }

        if (primerciModel.getPrimerci().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dodajte barem jedan primerak.");
            return;
        }

        Knjiga k = new Knjiga();
        k.setNaziv(naziv);
        k.setAutor(autor);
        k.setListaPrimeraka(primerciModel.getPrimerci());

        try {
            controller.UIController.getInstance().createKnjiga(k);
            JOptionPane.showMessageDialog(this, "Knjiga uspešno sačuvana.");

            if (parentForm != null) {
                parentForm.loadKnjige();
                parentForm.selectLastKnjigaRow();
                parentForm.refreshPrimerciLabelsForSelected();
            }

            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška prilikom čuvanja knjige: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSacuvajKnjiguActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniPrimerak;
    private javax.swing.JButton btnObrisiPrimerak;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnSacuvajKnjigu;
    private javax.swing.JButton btnSacuvajPrimerak;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblGodina;
    private javax.swing.JLabel lblIzdavac;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JTable tblPrimerak;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtGodina;
    private javax.swing.JTextField txtIzdavac;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables
}
