/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.zaduzenja;

import controller.UIController;
import domain.Clan;
import domain.Knjiga;
import domain.Primerak;
import domain.Radnik;
import domain.StavkaZaduzenja;
import domain.Zaduzenje;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.TableModelStavkaZaduzenja;
import models.TableModelZaduzenje;

/**
 *
 * @author Dejan Colic
 */
public class FormaZaduzenja extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormaZaduzenja.class.getName());
    private Radnik ulogovani;
    private List<StavkaZaduzenja> stavkeModel;
    private boolean stavkeChanged = false;
    private TableModelStavkaZaduzenja stavkeTableModel;
    private boolean isRefreshing = false;

    /**
     * Creates new form FormaZaduzenja
     */
    public FormaZaduzenja(Radnik ulogovani) {
        initComponents();
        stavkeModel = new ArrayList<>();
        stavkeTableModel = new TableModelStavkaZaduzenja(stavkeModel);
        tblStavke.setModel(stavkeTableModel);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Rad sa Zaduzenjima");
        setLocationRelativeTo(null);
        this.ulogovani = ulogovani;
        lblRadnikTekst.setText(ulogovani.getIme() + " " + ulogovani.getPrezime());

        btnIzmeniStavku.setEnabled(false);
        btnObrisiStavku.setEnabled(false);

        btnIzmeniZaduzenje.setEnabled(false);
        btnObrisiZaduzenje.setEnabled(false);

        tblStavke.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                boolean selected = tblStavke.getSelectedRow() >= 0;
                btnIzmeniStavku.setEnabled(selected);
                btnObrisiStavku.setEnabled(selected);
                if (selected) {
                    fillStavkaInputsFromSelected();
                }
            }
        });

        loadClanCombo();
        loadKnjigaCombo();

        if (cmbKnjiga.getItemCount() > 0) {
            cmbKnjiga.setSelectedIndex(0);
            Knjiga first = (Knjiga) cmbKnjiga.getSelectedItem();
            if (first != null) {
                loadPrimerakCombo(first);
            }
        }

        cmbKnjiga.addActionListener(evt -> {
            Knjiga selected = (Knjiga) cmbKnjiga.getSelectedItem();
            if (selected != null) {
                loadPrimerakCombo(selected);
            } else {
                cmbPrimerak.removeAllItems();
            }
        });
        loadZaduzenjaTable();

        tblZaduzenje.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                if (isRefreshing) {
                    return;
                }
                int row = tblZaduzenje.getSelectedRow();
                if (row == -1) {
                    btnIzmeniZaduzenje.setEnabled(false);
                    btnObrisiZaduzenje.setEnabled(false);
                    return;
                }
                if (stavkeChanged) {
                    int choice = JOptionPane.showConfirmDialog(
                            this,
                            "Imate izmene u stavkama koje nisu sačuvane. Ako nastavite, biće izgubljene.\nŽelite li da nastavite?",
                            "Potvrda",
                            JOptionPane.YES_NO_OPTION
                    );
                    if (choice != JOptionPane.YES_OPTION) {
                        tblZaduzenje.clearSelection();
                        btnIzmeniZaduzenje.setEnabled(false);
                        btnObrisiZaduzenje.setEnabled(false);
                        return;
                    }
                }
                loadStavkeForSelected();
                stavkeChanged = false;
                btnIzmeniZaduzenje.setEnabled(true);
                btnObrisiZaduzenje.setEnabled(true);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRadnik = new javax.swing.JLabel();
        lblRadnikTekst = new javax.swing.JLabel();
        lblDatumZaduzenja = new javax.swing.JLabel();
        txtDatumZaduzenja = new javax.swing.JTextField();
        lblClan = new javax.swing.JLabel();
        cmbClan = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        lblDatumRazduzenja = new javax.swing.JLabel();
        txtDatumRazduzenja = new javax.swing.JTextField();
        lblHint = new javax.swing.JLabel();
        lblPrimerak = new javax.swing.JLabel();
        cmbPrimerak = new javax.swing.JComboBox();
        lblNapomena = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();
        lblKnjiga = new javax.swing.JLabel();
        cmbKnjiga = new javax.swing.JComboBox();
        btnDodajStavku = new javax.swing.JButton();
        btnIzmeniStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblZaduzenje = new javax.swing.JTable();
        btnDodajZaduzenje = new javax.swing.JButton();
        btnIzmeniZaduzenje = new javax.swing.JButton();
        btnObrisiZaduzenje = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rad sa Zaduzenjima"));

        lblRadnik.setText("Radnik :");

        lblDatumZaduzenja.setText("Datum zaduzenja :");

        lblClan.setText("Clan :");

        cmbClan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke Zaduzenja"));

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        lblDatumRazduzenja.setText("Datum Razduzenja :");

        lblHint.setForeground(new java.awt.Color(0, 0, 255));
        lblHint.setText("(Ostaviti prazno ako knjiga nije vracena)");

        lblPrimerak.setText("Primerak :");

        lblNapomena.setText("Napomena :");

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane2.setViewportView(txtNapomena);

        lblKnjiga.setText("Knjiga :");

        cmbKnjiga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDodajStavku.setText("Dodaj Stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnIzmeniStavku.setText("Izmeni Stavku");
        btnIzmeniStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setText("Obrisi Stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDatumRazduzenja)
                                    .addComponent(lblPrimerak)
                                    .addComponent(lblNapomena)
                                    .addComponent(lblKnjiga))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDatumRazduzenja)
                                    .addComponent(cmbPrimerak, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                    .addComponent(cmbKnjiga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(37, 37, 37)
                                .addComponent(lblHint))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(btnDodajStavku)
                        .addGap(27, 27, 27)
                        .addComponent(btnIzmeniStavku)
                        .addGap(28, 28, 28)
                        .addComponent(btnObrisiStavku)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumRazduzenja)
                    .addComponent(txtDatumRazduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKnjiga)
                    .addComponent(cmbKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerak)
                    .addComponent(cmbPrimerak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNapomena)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajStavku)
                    .addComponent(btnIzmeniStavku)
                    .addComponent(btnObrisiStavku))
                .addGap(11, 11, 11))
        );

        tblZaduzenje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblZaduzenje);

        btnDodajZaduzenje.setText("Dodaj Zaduzenje");
        btnDodajZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajZaduzenjeActionPerformed(evt);
            }
        });

        btnIzmeniZaduzenje.setText("Izmeni Zaduzenje");
        btnIzmeniZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniZaduzenjeActionPerformed(evt);
            }
        });

        btnObrisiZaduzenje.setText("Obrisi Zaduzenje");
        btnObrisiZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiZaduzenjeActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatumZaduzenja)
                            .addComponent(lblRadnik)
                            .addComponent(lblClan))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRadnikTekst, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDatumZaduzenja)
                            .addComponent(cmbClan, 0, 339, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDodajZaduzenje)
                        .addGap(27, 27, 27)
                        .addComponent(btnIzmeniZaduzenje)
                        .addGap(28, 28, 28)
                        .addComponent(btnObrisiZaduzenje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNazad)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRadnik)
                    .addComponent(lblRadnikTekst))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumZaduzenja)
                    .addComponent(txtDatumZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClan)
                    .addComponent(cmbClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajZaduzenje)
                    .addComponent(btnIzmeniZaduzenje)
                    .addComponent(btnObrisiZaduzenje)
                    .addComponent(btnNazad))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        Primerak primerak = (Primerak) cmbPrimerak.getSelectedItem();
        if (primerak == null) {
            JOptionPane.showMessageDialog(this, "Odaberite primerak.");
            return;
        }

        Date datumZaduzenja;
        try {
            datumZaduzenja = new SimpleDateFormat("dd.MM.yyyy").parse(txtDatumZaduzenja.getText().trim());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unesite ispravan datum zaduženja pre dodavanja stavke.");
            return;
        }

        Date datumRazduzenja = null;
        String dt = txtDatumRazduzenja.getText().trim();
        if (!dt.isEmpty()) {
            try {
                datumRazduzenja = new SimpleDateFormat("dd.MM.yyyy").parse(dt);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Nevažeći format datuma. Koristite dd.MM.yyyy");
                return;
            }
            if (datumRazduzenja.before(datumZaduzenja)) {
                JOptionPane.showMessageDialog(this, "Datum razduženja ne može biti pre datuma zaduženja.");
                return;
            }
        }

        for (StavkaZaduzenja s : stavkeModel) {
            if (s.getPrimerak() != null && s.getPrimerak().getPrimerakID() == primerak.getPrimerakID()) {
                JOptionPane.showMessageDialog(this, "Taj primerak je već dodat u stavkama.");
                return;
            }
        }

        StavkaZaduzenja nova = new StavkaZaduzenja();
        nova.setPrimerak(primerak);
        nova.setDatumRazduzenja(datumRazduzenja);
        nova.setNapomena(txtNapomena.getText().trim());

        stavkeModel.add(nova);
        stavkeTableModel.setLista(stavkeModel);
        stavkeChanged = true;
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        int row = tblStavke.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati stavku za brisanje.");
            return;
        }

        TableModelStavkaZaduzenja model = (TableModelStavkaZaduzenja) tblStavke.getModel();
        StavkaZaduzenja selected = model.getAt(row);

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Da li ste sigurni da želite da obrišete stavku?",
                "Potvrda brisanja",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            stavkeModel.remove(selected);
            model.setLista(stavkeModel);
            stavkeChanged = true;
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnIzmeniStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniStavkuActionPerformed
        int row = tblStavke.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Izaberite stavku za izmenu.");
            return;
        }

        Primerak primerak = (Primerak) cmbPrimerak.getSelectedItem();
        if (primerak == null) {
            JOptionPane.showMessageDialog(this, "Odaberite primerak.");
            return;
        }

        Date datumZaduzenja;
        try {
            datumZaduzenja = new SimpleDateFormat("dd.MM.yyyy").parse(txtDatumZaduzenja.getText().trim());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unesite ispravan datum zaduženja.");
            return;
        }

        Date datumRazduzenja = null;
        String dt = txtDatumRazduzenja.getText().trim();
        if (!dt.isEmpty()) {
            try {
                datumRazduzenja = new SimpleDateFormat("dd.MM.yyyy").parse(dt);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Nevažeći format datuma. Koristite dd.MM.yyyy");
                return;
            }
            if (datumRazduzenja.before(datumZaduzenja)) {
                JOptionPane.showMessageDialog(this, "Datum razduženja ne može biti pre datuma zaduženja.");
                return;
            }
        }

        for (int i = 0; i < stavkeModel.size(); i++) {
            if (i == row) {
                continue;
            }
            StavkaZaduzenja s = stavkeModel.get(i);
            if (s.getPrimerak() != null && s.getPrimerak().getPrimerakID() == primerak.getPrimerakID()) {
                JOptionPane.showMessageDialog(this, "Taj primerak je već dodat u stavkama.");
                return;
            }
        }

        StavkaZaduzenja target = stavkeModel.get(row);
        target.setPrimerak(primerak);
        target.setDatumRazduzenja(datumRazduzenja);
        target.setNapomena(txtNapomena.getText().trim());

        stavkeTableModel.fireTableRowsUpdated(row, row);
        stavkeChanged = true;
    }//GEN-LAST:event_btnIzmeniStavkuActionPerformed

    private void btnDodajZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajZaduzenjeActionPerformed
        String datumText = txtDatumZaduzenja.getText().trim();
        if (datumText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite datum zaduženja.");
            return;
        }

        Date datumZaduzenja;
        try {
            datumZaduzenja = new SimpleDateFormat("dd.MM.yyyy").parse(datumText);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Nevažeći format datuma zaduženja. Koristite dd.MM.yyyy");
            return;
        }

        Clan clan = (Clan) cmbClan.getSelectedItem();
        if (clan == null) {
            JOptionPane.showMessageDialog(this, "Odaberite člana.");
            return;
        }

        if (stavkeModel == null || stavkeModel.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dodajte bar jednu stavku zaduženja.");
            return;
        }

        Zaduzenje z = new Zaduzenje();
        z.setDatumZaduzenja(datumZaduzenja);
        z.setClan(clan);
        z.setRadnik(ulogovani);

        StavkaZaduzenja[] stavke = stavkeModel.toArray(new StavkaZaduzenja[0]);
        z.setStavkeZaduzenja(stavke);

        try {
            UIController.getInstance().createZaduzenje(z);
            JOptionPane.showMessageDialog(this, "Zaduženje je sačuvano.");

            isRefreshing = true;
            loadZaduzenjaTable();

            int target = tblZaduzenje.getRowCount() - 1;
            if (target >= 0) {
                tblZaduzenje.setRowSelectionInterval(target, target);
                loadStavkeForSelected();
            }

            stavkeModel.clear();
            stavkeTableModel.setLista(stavkeModel);
            txtDatumZaduzenja.setText("");
            txtDatumRazduzenja.setText("");
            txtNapomena.setText("");
            stavkeChanged = false;
            isRefreshing = false;

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri čuvanju zaduženja: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnDodajZaduzenjeActionPerformed

    private void btnObrisiZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiZaduzenjeActionPerformed
        int row = tblZaduzenje.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Izaberite zaduženje za brisanje.");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Da li ste sigurni da želite da obrišete zaduženje?",
                "Potvrda brisanja",
                JOptionPane.YES_NO_OPTION
        );
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        TableModelZaduzenje model = (TableModelZaduzenje) tblZaduzenje.getModel();
        Zaduzenje z = model.getZaduzenjeAt(row);

        try {
            UIController.getInstance().deleteZaduzenje(z);
            JOptionPane.showMessageDialog(this, "Zaduženje je obrisano.");
            loadZaduzenjaTable();
            stavkeModel.clear();
            ((TableModelStavkaZaduzenja) tblStavke.getModel()).setLista(stavkeModel);
            stavkeChanged = false;
            txtDatumZaduzenja.setText("");
            txtDatumRazduzenja.setText("");
            txtNapomena.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška prilikom brisanja: " + e.getMessage());
        }
    }//GEN-LAST:event_btnObrisiZaduzenjeActionPerformed

    private void btnIzmeniZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniZaduzenjeActionPerformed
        int row = tblZaduzenje.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Izaberite zaduženje za izmenu.");
            return;
        }

        String datumText = txtDatumZaduzenja.getText().trim();
        if (datumText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite datum zaduženja.");
            return;
        }

        Date datumZaduzenja;
        try {
            datumZaduzenja = new SimpleDateFormat("dd.MM.yyyy").parse(datumText);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Nevažeći format datuma zaduženja. Koristite dd.MM.yyyy");
            return;
        }

        Clan clan = (Clan) cmbClan.getSelectedItem();
        if (clan == null) {
            JOptionPane.showMessageDialog(this, "Odaberite člana.");
            return;
        }

        TableModelZaduzenje tm = (TableModelZaduzenje) tblZaduzenje.getModel();
        Zaduzenje selected = tm.getZaduzenjeAt(row);

        Zaduzenje z = new Zaduzenje();
        z.setZaduzenjeID(selected.getZaduzenjeID());
        z.setDatumZaduzenja(datumZaduzenja);
        z.setClan(clan);
        z.setRadnik(ulogovani);
        z.setStavkeZaduzenja(stavkeModel.toArray(new StavkaZaduzenja[0]));

        try {
            UIController.getInstance().updateZaduzenje(z);
            JOptionPane.showMessageDialog(this, "Zaduženje je izmenjeno.");

            isRefreshing = true;
            loadZaduzenjaTable();

            for (int i = 0; i < tblZaduzenje.getRowCount(); i++) {
                if (((TableModelZaduzenje) tblZaduzenje.getModel()).getZaduzenjeAt(i).getZaduzenjeID() == z.getZaduzenjeID()) {
                    tblZaduzenje.setRowSelectionInterval(i, i);
                    loadStavkeForSelected();
                    break;
                }
            }

            stavkeChanged = false;
            isRefreshing = false;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri izmeni zaduženja: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnIzmeniZaduzenjeActionPerformed

    private void loadClanCombo() {
        try {
            List<Clan> clanovi = UIController.getInstance().getAllClan();
            cmbClan.removeAllItems();
            for (Clan c : clanovi) {
                cmbClan.addItem(c);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Greška prilikom učitavanja članova: " + e.getMessage());
        }
    }

    private void loadZaduzenjaTable() {
        try {
            List<Zaduzenje> lista = UIController.getInstance().getAllZaduzenje();
            TableModelZaduzenje model = new TableModelZaduzenje(lista);
            tblZaduzenje.setModel(model);
            tblZaduzenje.clearSelection();
            btnIzmeniZaduzenje.setEnabled(false);
            btnObrisiZaduzenje.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška prilikom učitavanja zaduženja: " + e.getMessage());
        }
    }

    private void loadStavkeForSelected() {
        int row = tblZaduzenje.getSelectedRow();
        if (row < 0) {
            stavkeModel.clear();
            stavkeTableModel.setLista(stavkeModel);
            return;
        }

        TableModelZaduzenje model = (TableModelZaduzenje) tblZaduzenje.getModel();
        Zaduzenje z = model.getZaduzenjeAt(row);

        if (z.getDatumZaduzenja() != null) {
            txtDatumZaduzenja.setText(new SimpleDateFormat("dd.MM.yyyy").format(z.getDatumZaduzenja()));
        } else {
            txtDatumZaduzenja.setText("");
        }

        if (z.getClan() != null) {
            for (int i = 0; i < cmbClan.getItemCount(); i++) {
                Clan c = (Clan) cmbClan.getItemAt(i);
                if (c.getClanID() == z.getClan().getClanID()) {
                    cmbClan.setSelectedIndex(i);
                    break;
                }
            }
        }

        try {
            List<StavkaZaduzenja> stavke = UIController.getInstance().getStavkeForZaduzenje(z);
            stavkeModel.clear();
            stavkeModel.addAll(stavke);
            stavkeTableModel.setLista(stavkeModel);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška prilikom učitavanja stavki: " + e.getMessage());
        }
    }

    private void loadKnjigaCombo() {
        try {
            List<Knjiga> knjige = UIController.getInstance().getAllKnjiga();
            cmbKnjiga.removeAllItems();
            for (Knjiga k : knjige) {
                cmbKnjiga.addItem(k);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Greška prilikom učitavanja knjiga: " + e.getMessage());
        }
    }

    private void loadPrimerakCombo(Knjiga knjiga) {
        try {
            List<Primerak> available = UIController.getInstance().getAvailablePrimerciForKnjiga(knjiga);
            LinkedHashMap<Integer, Primerak> map = new LinkedHashMap<>();
            for (Primerak p : available) {
                map.put(p.getPrimerakID(), p);
            }
            for (StavkaZaduzenja s : stavkeModel) {
                if (s.getPrimerak() != null && s.getPrimerak().getKnjiga() != null
                        && s.getPrimerak().getKnjiga().getKnjigaID() == knjiga.getKnjigaID()) {
                    map.put(s.getPrimerak().getPrimerakID(), s.getPrimerak());
                }
            }
            cmbPrimerak.removeAllItems();
            for (Primerak p : map.values()) {
                cmbPrimerak.addItem(p);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška prilikom učitavanja primeraka: " + e.getMessage());
        }
    }

    private void fillStavkaInputsFromSelected() {
        int row = tblStavke.getSelectedRow();
        if (row < 0) {
            return;
        }

        TableModelStavkaZaduzenja model = (TableModelStavkaZaduzenja) tblStavke.getModel();
        StavkaZaduzenja s = model.getAt(row);

        if (s.getPrimerak() != null && s.getPrimerak().getKnjiga() != null) {
            Knjiga k = s.getPrimerak().getKnjiga();
            cmbKnjiga.setSelectedItem(k);
            loadPrimerakCombo(k);
            cmbPrimerak.setSelectedItem(s.getPrimerak());
        } else if (s.getPrimerak() != null) {
            cmbPrimerak.setSelectedItem(s.getPrimerak());
        }

        if (s.getDatumRazduzenja() != null) {
            txtDatumRazduzenja.setText(new java.text.SimpleDateFormat("dd.MM.yyyy").format(s.getDatumRazduzenja()));
        } else {
            txtDatumRazduzenja.setText("");
        }
        txtNapomena.setText(s.getNapomena() == null ? "" : s.getNapomena());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnDodajZaduzenje;
    private javax.swing.JButton btnIzmeniStavku;
    private javax.swing.JButton btnIzmeniZaduzenje;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnObrisiZaduzenje;
    private javax.swing.JComboBox cmbClan;
    private javax.swing.JComboBox cmbKnjiga;
    private javax.swing.JComboBox cmbPrimerak;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblClan;
    private javax.swing.JLabel lblDatumRazduzenja;
    private javax.swing.JLabel lblDatumZaduzenja;
    private javax.swing.JLabel lblHint;
    private javax.swing.JLabel lblKnjiga;
    private javax.swing.JLabel lblNapomena;
    private javax.swing.JLabel lblPrimerak;
    private javax.swing.JLabel lblRadnik;
    private javax.swing.JLabel lblRadnikTekst;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTable tblZaduzenje;
    private javax.swing.JTextField txtDatumRazduzenja;
    private javax.swing.JTextField txtDatumZaduzenja;
    private javax.swing.JTextArea txtNapomena;
    // End of variables declaration//GEN-END:variables
}
